---
- name: this playbook is for Jenkins master
  hosts: master 
  become: yes

  tasks: 
    - name: installing git package
      yum: 
         name: git 
         state: latest  

    - name: Installing web-service on master 
      yum: 
        name: httpd
        state: latest
    
    - name: enabling and restarting httpd
      service: 
         name: httpd
         state: restarted
         enabled: yes
